name: PushToCephProduction

on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'config/**'
      - 'layouts/**'
      - 'assets/**'
      - '.github/workflows/deploy-ceph-prod.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: OpenizePtyLtd/www.fileformat.app
        token: ${{ secrets.REPO_TOKEN }}
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.125.7'
        extended: true

    - name: Install Dependencies
      run: |
        npm install -D --save autoprefixer
        npm install -D --save postcss-cli

    - name: Build Site
      run: hugo --config "./config/config-ceph-fileformat-app.toml" --environment production --minify --cleanDestinationDir

    - name: Generate Build Info
      run: |
        mkdir -p public
        cat > public/build-info.txt << 'EOF'
        Branch: ${{ github.ref_name }}
        Commit: ${{ github.sha }}
        Author: ${{ github.actor }}
        Datetime: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        EOF

    - name: Deploy to Ceph Production
      run: |
        hugo --config "./config/config-ceph-fileformat-app.toml" deploy --target production-ceph --environment production --maxDeletes -1 --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CEPH_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CEPH_SECRET_KEY }}

    - name: Purge Bunny CDN cache
      env:
        BUNNYNET_ACCESSKEY: ${{ secrets.BUNNYNET_ACCESSKEY }}
      run: |
        echo Purging https://www.fileformat.app
        curl -siG -H "X-Api-Key: $BUNNYNET_ACCESSKEY" --data-urlencode "url=https://www.fileformat.app/*" "https://api.dynabic.com/bn/purge?async=true"